version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:latest
    container_name: sentiment_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
